language: node_js
node_js:
    - 11
before_install:
    - cd app/
    - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv
      -in gae-keys.json.enc -out gae-keys.json -d

before_script:
    - npm run test-build

before_deploy:
    - npm run clean
    - npm run build

deploy:
    provider: gae
    keyfile: gae-keys.json
    project: final-year-project-257911
    skip_cleanup: true
