language: node_js
node_js:
    - 11
before_install:
    - cd app/

before_deploy:
    - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv
      -in gae-keys.json.enc -out gae-keys.json -d
    - wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
    - sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
    - npm run clean
    - npm run build

deploy:
    provider: gae
    keyfile: gae-keys.json
    project: final-year-project-257911
    skip_cleanup: true
    no_promote: true
    on:
        tags: true
