runtime: go111

main: ./go/server/main.go

handlers:
    - url: /(.*\.(ico|xml|webmanifest|json|png|js|html|css|map))$
      static_files: dist/\1
      secure: always
      upload: dist/.*\.(ico|xml|webmanifest|json|png|js|html|css|map)$

    - url: /$
      script: auto
      secure: always
