runtime: go115

main: ./go/server/main.go

handlers:
    - url: /$
      static_files: dist/splash.html
      secure: always
      upload: dist/splash.html

    - url: /(.*\.(gif|ico|xml|webmanifest|json|png|js|html|css|map|svg))$
      static_files: dist/\1
      secure: always
      upload: dist/.*\.(gif|ico|xml|webmanifest|json|png|js|html|css|map|svg)$

    - url: /editor/.*
      script: auto
      secure: always
