version: "3.9"
services:
  datastore:
    container_name: try-setanta_datastore
    expose:
      - 8081
    image: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: ["gcloud", "beta", "emulators", "datastore", "start",
      "--project=test-project", "--host-port=0.0.0.0:8081", "--data-dir=/var/datastore"]
    volumes:
      - 'datastore_data:/var/datastore'

  backend:
    container_name: try-setanta_backend
    build:
      context: '.'
      dockerfile: Dockerfile.backend
    image: try-setanta-backend
    depends_on:
      - datastore
    environment:
      DATASTORE_EMULATOR_HOST: datastore:8081
      DATASTORE_PROJECT_ID: test-project
    volumes:
      - '../.:/app'

  frontend:
    container_name: try-setanta_frontend
    build:
      context: '..'
      dockerfile: local_dev/Dockerfile.frontend
    image: try-setanta-frontend
    depends_on:
      - backend
    volumes:
      - '../.:/app'
    ports:
      - '80:80'

volumes:
  datastore_data:
